id: cors-misconfiguration

info:
  name: CORS Misconfiguration
  author: Kalkaneus Team
  severity: medium
  description: Detects CORS misconfigurations that allow arbitrary origins
  reference:
    - https://portswigger.net/web-security/cors
  tags: cors,misconfiguration,security-headers

http:
  - method: GET
    path:
      - "{{BaseURL}}"
    
    headers:
      Origin: https://evil.com
    
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "Access-Control-Allow-Origin: https://evil.com"
          - "Access-Control-Allow-Origin: *"
        condition: or
        
      - type: word
        part: header
        words:
          - "Access-Control-Allow-Credentials: true"
